<testsuites id="" name="" tests="4" failures="1" skipped="0" errors="0" time="29.41488">
<testsuite name="azure.spec.ts" timestamp="2025-05-07T07:16:36.277Z" hostname="chromium" tests="2" failures="1" skipped="0" time="22.178" errors="0">
<testcase name="Test 1" classname="azure.spec.ts" time="17.487">
<failure message="azure.spec.ts:3:5 Test 1" type="FAILURE">
<![CDATA[  [chromium] › azure.spec.ts:3:5 › Test 1 ──────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveTitle(expected)

    Locator: locator(':root')
    Expected string: "Swag Lab"
    Received string: "Swag Labs"
    Call log:
      - expect.toHaveTitle with timeout 5000ms
      - waiting for locator(':root')
        8 × locator resolved to <html lang="en">…</html>
          - unexpected value "Swag Labs"


      4 | await page.goto("https://saucedemo.com");
      5 | console.log("Reached the Page");
    > 6 | await expect(page).toHaveTitle('Swag Lab');
        |                    ^
      7 | })
      8 |
      9 | test('Test 2' , async({page})=>{
        at C:\Users\tejsharma\Documents\Playwright\azurecicd2\tests\azure.spec.ts:6:20

    Error Context: ..\test-results\azure-Test-1-chromium\error-context.md
]]>
</failure>
<system-out>
<![CDATA[Reached the Page

[[ATTACHMENT|test-results\azure-Test-1-chromium\error-context.md]]
]]>
</system-out>
</testcase>
<testcase name="Test 2" classname="azure.spec.ts" time="4.691">
<system-out>
<![CDATA[Reached the Page - 2
123
234
]]>
</system-out>
</testcase>
</testsuite>
<testsuite name="example.spec.ts" timestamp="2025-05-07T07:16:36.277Z" hostname="chromium" tests="2" failures="0" skipped="0" time="20.528" errors="0">
<testcase name="Test 1" classname="example.spec.ts" time="9.302">
<system-out>
<![CDATA[Reached the Page
]]>
</system-out>
</testcase>
<testcase name="Test 2" classname="example.spec.ts" time="11.226">
<system-out>
<![CDATA[Reached the Page - 2
123
2345
]]>
</system-out>
</testcase>
</testsuite>
</testsuites>